[package]
name = "pasta_curves"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zkstd = { path = "../zkstd", default-features = false }
jub-jub = { path = "../jubjub", default-features = false }
bls-12-381 = { path = "../bls12_381", default-features = false }
serde = { version = "1.0.102", default-features = false, features = ["derive"] }
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }

[dev-dependencies]
paste = "1.0.11"
rand_core = { version="0.6.4", default-features = false, features = ["getrandom"]}