version: '3'
services:
  elgamal:
    image: sagemath/sagemath:latest
    container_name: elgamal
    tty: true
    stdin_open: true
    working_dir: /app
    volumes:
      - .:/app
  ganache:
      image: trufflesuite/ganache-cli
      container_name: ganache
      tty: true
      stdin_open: true
      ports:
        - 8545:8545
      command: -m="belt prize arrow cabbage banner proof word above ability helmet design rely" --networkId=5777 -l 80000000000 --account="0x6f35a186477bc4045d9cbbe077a18a19af41eb0a11cf751b716443b184f974b5,100000000000000000000"
  transactor:
      environment:
        ENDPOINT: http://ganache:8545

