[package]
authors = [
    'ashWhiteHat<phantomofrotten@gmail.com>',
    'KiriosK<KiriosK@yandex.ru>'
]
name = "zkstd"
description = 'zero knowledge proof standard library'
version = "0.0.16"
edition = "2021"
license = "Apache-2.0"
homepage = 'https://github.com/KogarashiNetwork/Kogarashi/'
repository = 'https://github.com/KogarashiNetwork/Kogarashi/'
readme = 'README.md'
categories = ["cryptography"]
keywords = ["zkp", "blockchain", "elliptic-curve"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs", "--html-in-header", "katex-header.html"]

[dependencies]
paste = "1.0.11"
rand_core = { version="0.6.4", default-features = false }
sp-std = { version = '3.0.0', default-features = false }
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.102", default-features = false, features = ["derive"] }

[dev-dependencies]
jub-jub = { path = '../jubjub', default-features = false }
bls-12-381 = { path = '../bls12_381', default-features = false }

[[test]]
name = "arithmetics"
path = "tests/limbs.rs"

[features]
default = ["std"]
std = ["rand_core/getrandom"]
