[book]
authors = ['NoCtrlZ<shinsaku.ashizawa@artree.co.jp>']
multilingual = false
src = "book"
title = "Zero Network Documentation"

[build]
build-dir = "docs"

[output.html]
mathjax-support = true
latex = true
