[package]
authors = [
    'ashWhiteHat<phantomofrotten@gmail.com>',
    'KiriosK<KiriosK@yandex.ru>'
]
name = "zero-network"
description = 'Zero network privacy-preserving blockchain'
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
homepage = 'https://github.com/zero-network/zero/'
repository = 'https://github.com/zero-network/zero/'
readme = 'README.md'

[dependencies]
# primitive
zero-bls12-381 = { version = "0.1.10", default-features = false }
zero-crypto = { version = "0.1.10", default-features = false }
zero-elgamal = { version = "0.1.10", default-features = false }
zero-jubjub = { version = "0.1.10", default-features = false }
zero-kzg = { version = "0.1.10", default-features = false }
zero-pairing = { version = "0.1.10", default-features = false }
zero-plonk = { version = "0.1.10", default-features = false }

# pallet
confidential_transfer = { path = "./pallets/confidential_transfer", default-features = false }
pallet-plonk = { path = "./pallets/plonk", default-features = false }
pallet-encrypted-balance = { path = "./pallets/encrypted_balance", default-features = false }

[dev-dependencies]
rand = { version = "0.8", default-features = false }
rand_core = { version="0.6", default-features = false }
sp-io = { default-features = false, version = '3.0.0' }
sp-core = { default-features = false, version = '3.0.0' }
sp-runtime = { default-features = false, version = '3.0.0' }
serde = { version = "1.0.102", default-features = false, features = ["derive"] }
codec = { version = '2.0.0', default-features = false, features = ['derive'], package = 'parity-scale-codec' }
frame-system = { default-features = false, version = '3.0.0' }
frame-support = { default-features = false, version = '3.0.0' }

[workspace]
members = [
    "primitive/bls12_381",
    "primitive/crypto",
    "primitive/elgamal",
    "primitive/jubjub",
    "primitive/kzg",
    "primitive/pairing",
    "primitive/plonk",
    "pallets/confidential_transfer",
    "pallets/encrypted_balance",
    "pallets/plonk"
]

[features]
default = ["std"]
std = [
    'confidential_transfer/std',
    'pallet-plonk/std',
    'pallet-encrypted-balance/std',
]
