[package]
authors = [
    'ashWhiteHat<phantomofrotten@gmail.com>',
    'KiriosK<KiriosK@yandex.ru>'
]
name = "zero-network"
description = 'Kogarashi Network privacy-preserving blockchain'
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
homepage = 'https://github.com/KogarashiNetwork/Kogarashi/'
repository = 'https://github.com/KogarashiNetwork/Kogarashi/'
readme = 'README.md'

[dependencies]
# primitive
bls-12-381 = { path = "./primitive/bls12_381", default-features = false }
zkstd = { path = "./primitive/zkstd", default-features = false }
lifted-elgamal = { path = "./primitive/elgamal", default-features = false }
jub-jub = { path = "./primitive/jubjub", default-features = false }
poly-commit = { path = "./primitive/poly", default-features = false }
ec-pairing = { path = "./primitive/pairing", default-features = false }
zero-plonk = { path = "./primitive/plonk", default-features = false }

# pallet
pallet-plonk = { path = "./pallets/plonk", default-features = false }
pallet-encrypted-balance = { path = "./pallets/encrypted_balance", default-features = false }
confidential_transfer = { path = "./pallets/confidential_transfer", default-features = false }

[dev-dependencies]
criterion = "0.4.0"
rand = { version = "0.8"}
rand_core = { version="0.6.4", default-features = false }
# SBP-M1 review: fetch `sp-io`, `sp-core`, `sp-runtime`, `frame-support`, `frame-system` directly from GitHub for specific Substrate/Cumulus/Polkadot version
sp-io = { default-features = false, version = '3.0.0' }
sp-core = { default-features = false, version = '3.0.0' }
sp-runtime = { default-features = false, version = '3.0.0' }
serde = { version = "1.0.102", default-features = false, features = ["derive"] }
codec = { version = '2.0.0', default-features = false, features = ['derive'], package = 'parity-scale-codec' }
frame-system = { default-features = false, version = '3.0.0' }
frame-support = { default-features = false, version = '3.0.0' }

[workspace]
members = [
    "client",
    "pallets/confidential_transfer",
    "pallets/encrypted_balance",
    "pallets/plonk",
    "primitive/bls12_381",
    "primitive/elgamal",
    "primitive/jubjub",
    "primitive/pairing",
    "primitive/plonk",
    "primitive/poly",
    "primitive/r1cs",
    "primitive/redjubjub",
    "primitive/zkstd",
    "zkruntime/redjubjub",
    "zkruntime/runtime"
]

[profile.release]
panic = "abort"
codegen-units = 1
overflow-checks = false
debug = true

[profile.bench]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
incremental = false
codegen-units = 1

[features]
default = ["std"]
std = [
    'confidential_transfer/std',
    'pallet-plonk/std',
    'pallet-encrypted-balance/std',
]

[[bench]]
name = "confidential_transfer"
harness = false

[[bench]]
name = "pairing"
harness = false

[[bench]]
name = "jubjub_curve"
harness = false

[[bench]]
name = "bls12_381_curve"
harness = false

[[bench]]
name = "jubjub_field"
harness = false

[[bench]]
name = "bls12_381_field"
harness = false

[[bench]]
name = "msm"
harness = false
