[package]
name = "zero-network"
description = 'Zero network blockchain'
version = "0.1.0"
authors = ['NoCtrlZ<phantomofrotten@gmail.com>']
edition = "2021"
license = "Apache-2.0"

[dependencies]
zero-jubjub = { version = "0.1", default-features = false, path = "./primitive/jubjub" }
zero-elgamal = { version = "0.1", default-features = false, path = "./primitive/elgamal" }
zero-plonk = { version = "0.1", default-features = false, path = "./primitive/snarks/plonk" }
zero-poly = { version = "0.1", default-features = false, path = "./primitive/snarks/poly" }
pallet-confidential-transfer = { version = "0.1", default-features = false, path = "./pallets/confidential_transfer" }
rand_core = { version = "0.5", features = ["std"] }

[dev-dependencies]
ed25519 = "1.3"
ed25519-dalek = "1"
rand_core = "0.6"

[workspace]
members = [
    "primitive/jubjub",
    "primitive/elgamal",
    "primitive/snarks/plonk",
    "primitive/snarks/poly",
    "pallets/confidential_smart_contract",
    "pallets/confidential_transfer"
]

[features]
default = ['std']
std = [
    'pallet-confidential-transfer/std'
]
