[package]
name = "zero-network"
description = 'Zero network blockchain'
version = "0.1.0"
authors = ['NoCtrlZ<shinsaku.ashizawa@artree.co.jp>']
edition = "2021"
license = "Apache-2.0"

[dependencies]
zero-jubjub = { version = "0.1", default-features = false, path = "./snarks/jubjub" }
zero-plonk = { version = "0.1", default-features = false, path = "./snarks/plonk" }
pallet-confidential-transfer = { version = "0.1", default-features = false, path = "./pallets/confidential_transfer" }

[dev-dependencies]
ed25519 = "1.3"
ed25519-dalek = "1"
rand_core = { version = "0.5", features = ["std"] }

[workspace]
members = [
    "snarks/jubjub",
    "snarks/plonk",
    "pallets/confidential_transfer",
]

[features]
default = ['std']
std = [
    'pallet-confidential-transfer/std'
]
