[package]
name = "zero-network"
description = 'Zero network blockchain'
version = "0.1.0"
authors = ['AshWhiteHat<phantomofrotten@gmail.com>']
edition = "2021"
license = "Apache-2.0"

[dependencies]
# primitive
zero-bls12-381 = { default-features = false, path = "./primitive/bls12_381" }
zero-circuits = { default-features = false, path = "./primitive/circuits" }
zero-crypto = { default-features = false, path = "./primitive/crypto" }
zero-elgamal = { default-features = false, path = "./primitive/elgamal" }
zero-jubjub = { default-features = false, path = "./primitive/jubjub" }
zero-kzg = { default-features = false, path = "./primitive/kzg" }
zero-pairing = { default-features = false, path = "./primitive/pairing" }
zero-plonk = { default-features = false, path = "./primitive/plonk" }

# pallet
confidential_transfer = { default-features = false, path = "./pallets/confidential_transfer" }
pallet-plonk = { default-features = false, path = "./pallets/plonk" }
pallet-encrypted-balance = { default-features = false, path = "./pallets/encrypted_balance" }

frame-support = { version = "3.0.0" }

[dev-dependencies]
criterion = "0.4.0"
rand = { version = "0.8", default-features = false }

[workspace]
members = [
    "primitive/bls12_381",
    "primitive/circuits",
    "primitive/crypto",
    "primitive/elgamal",
    "primitive/jubjub",
    "primitive/kzg",
    "primitive/pairing",
    "primitive/plonk",
    "pallets/confidential_transfer",
    "pallets/encrypted_balance",
    "pallets/plonk"
]

[[bench]]
name = "circuit"
harness = false

[[bench]]
name = "pairing"
harness = false

[[bench]]
name = "jubjub_curve"
harness = false

[[bench]]
name = "bls12_381_curve"
harness = false

[[bench]]
name = "jubjub_field"
harness = false

[[bench]]
name = "bls12_381_field"
harness = false

[[bench]]
name = "msm"
harness = false

[profile.release]
panic = "abort"
codegen-units = 1
overflow-checks = false
debug = true

[profile.bench]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
incremental = false
codegen-units = 1