[package]
name = "zero-network"
description = 'Zero network blockchain'
version = "0.1.0"
authors = ['NoCtrlZ<phantomofrotten@gmail.com>']
edition = "2021"
license = "Apache-2.0"

[dependencies]
zero-bls12-381 = { version = "0.1", default-features = false, path = "./primitive/bls12_381" }
zero-crypto = { version = "0.1", default-features = false, path = "./primitive/crypto" }
zero-elgamal = { version = "0.1", default-features = false, path = "./primitive/elgamal" }
zero-jubjub = { version = "0.1", default-features = false, path = "./primitive/jubjub" }
zero-kzg = { version = "0.1", path = "./primitive/kzg" }
zero-pairing = { version = "0.1", default-features = false, path = "./primitive/pairing" }
pallet-encrypted-balance = { version = "0.1", default-features = false, path = "./pallets/encrypted_balance" }
rand_core = { version = "0.5", features = ["std"] }

[dev-dependencies]
ed25519 = "1.3"
ed25519-dalek = "1"
rand_core = "0.6"

[workspace]
members = [
    "primitive/bls12_381",
    "primitive/circuits",
    "primitive/crypto",
    "primitive/elgamal",
    "primitive/jubjub",
    "primitive/kzg",
    "primitive/pairing",
    "primitive/plonk",
    "pallets/confidential_transfer",
    "pallets/encrypted_balance",
    "pallets/plonk"
]

[features]
default = ['std']
std = [
    'pallet-encrypted-balance/std'
]
