[package]
name = "zero-network"
description = 'Zero network blockchain'
version = "0.1.0"
authors = ['NoCtrlZ<shinsaku.ashizawa@artree.co.jp>']
edition = "2021"
license = "Apache-2.0"

[dependencies]
eddy = { version = "0.1", default-features = false, path = "./core/eddy" }

[workspace]
members = [
    "core/eddy"
]
