site_name: Kogarashi Network
theme:
  name: material
nav:
  - Introduction: index.md
  - Infrastructure:
    - 'Abstract': infrastructure.md
    - What is privacy?: what_is_privacy.md
    - Hide Transfer Amount: hide_transfer_amount.md
    - Gas Limit: gas_limit.md
    - Zero Knowledge Scheme: zero_knowledge_scheme.md
  - Tutorial:
    - 'Abstract': tutorial.md
    - Plonk Pallet: plonk_pallet.md
    - Confidential Transfer Pallet: confidential_transfer_pallet.md
    - RedDSA Wallet: reddsa_wallet.md
  - Constraints:
    - 'Abstract': constraints.md
    - Confidential Transfer Constraints: confidential_transfer_constraints.md
  - Technical:
    - 'Abstract': technical.md
    - Stealth Address: stealth_address.md
    - Pedersen Commitment: pedersen_commitment.md
    - Zero Knowledge Proof:
      - 'Abstract': non_interactive_zero_knowlege_proof.md
      - QAP: qap.md
      - Polynomial Commitment: polynomial_commitment.md
      - Homomorphic Encryption: homomorphic_encryption.md
    - RedDSA Signature: reddsa_signature.md
  - Help:
    - Frequent Errors: frequent_errors.md
site_dir: docs
docs_dir: book
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - mdx_math
  - codehilite
