site_name: Kogarashi Network
theme:
  name: material
nav:
  - Introduction: index.md
  - Infrastructure:
    - 'Abstract': infrastructure/index.md
    - What is privacy?: infrastructure/what_is_privacy.md
    - Hide Transfer Amount: infrastructure/hide_transfer_amount.md
    - Gas Limit: infrastructure/gas_limit.md
    - Zero Knowledge Scheme: infrastructure/zero_knowledge_scheme.md
  - Tutorial:
    - 'Abstract': tutorial/index.md
    - Plonk Pallet: tutorial/plonk_pallet.md
    - Confidential Transfer Pallet: tutorial/confidential_transfer_pallet.md
    - RedDSA Wallet: tutorial/reddsa_wallet.md
  - Constraints:
    - 'Abstract': constraints/index.md
    - Confidential Transfer Constraints: constraints/confidential_transfer_constraints.md
  - Technical:
    - 'Abstract': technical/index.md
    - Stealth Address: technical/stealth_address.md
    - Pedersen Commitment: technical/pedersen_commitment.md
    - Zero Knowledge Proof:
      - 'Abstract': technical/non_interactive_zero_knowlege_proof.md
      - QAP: technical/qap.md
      - Polynomial Commitment: technical/polynomial_commitment.md
      - Homomorphic Encryption: technical/homomorphic_encryption.md
    - RedDSA Signature: technical/reddsa_signature.md
  - Help:
    - Frequent Errors: frequent_errors.md
site_dir: docs
docs_dir: book
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - mdx_math
  - codehilite
