[package]
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
description = 'FRAME pallet template for defining custom runtime logic.'
edition = '2018'
homepage = 'https://substrate.dev'
license = 'Unlicense'
name = 'pallet-template'
readme = 'README.md'
repository = 'https://github.com/substrate-developer-hub/substrate-node-template/'
version = '3.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { default-features = false, features = ['derive'], package = 'parity-scale-codec', version = '2.0.0' }
frame-system = { default-features = false, tag = 'v3.0.0', git = "https://github.com/paritytech/substrate" }
frame-support = { default-features = false, tag = 'v3.0.0', git = "https://github.com/paritytech/substrate" }
frame-benchmarking = { default-features = false, optional = true, tag = 'v3.1.0', git = "https://github.com/paritytech/substrate" }
sp-std = { default-features = false, tag = 'v3.0.0', git = "https://github.com/paritytech/substrate" }

[dev-dependencies]
serde = { version = "1.0.119" }
sp-core = { default-features = false, tag = 'v3.0.0', git = "https://github.com/paritytech/substrate" }
sp-io = { default-features = false, tag = 'v3.0.0', git = "https://github.com/paritytech/substrate" }
sp-runtime = { default-features = false, tag = 'v3.0.0', git = "https://github.com/paritytech/substrate" }

[features]
default = ['std']
std = [
	'codec/std',
	'frame-support/std',
	'frame-system/std',
	'frame-benchmarking/std',
	'sp-std/std',
]
runtime-benchmarks = [
	'frame-benchmarking',
	'frame-support/runtime-benchmarks',
	'frame-system/runtime-benchmarks',
]
