[package]
authors = ['AshWhiteHat<phantomofrotten@gmail.com>']
name = "zero-elgamal"
description = 'lifted elgamal encryption implementation'
version = "0.2.0"
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parity-scale-codec = { version = "2.1.0", default-features = false, features = ["derive"] }
zero-jubjub = { version = '0.2.0', default-features = false }
zero-crypto = { version = '0.2.1', default-features = false }
serde = { version = "1.0.125", default-features = false, features = ["derive"] }
num-traits = { version = "0.2.15", default-features = false }

[dev-dependencies]
rand = { version = "0.8", default-features = false }
rand_xorshift = { version = "0.3", default-features = false }
proptest = "1"
