[package]
name = "pallet-zk-rollup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
zkstd = { path = "../zkstd", default-features = false }
jub-jub = { path = "../jubjub", default-features = false }
ark-std = "0.4.0"
zero-plonk = { path = "../plonk", default-features = false }
zksnarks = { path = "../zksnarks", default-features = false }
ec-pairing = { path = "../pairing", default-features = false }
red-jubjub = { path = "../redjubjub", default-features = false}
rand_core = { version="0.6.4", features = ["getrandom"] }
bls-12-381 = { path = '../bls12_381', default-features = false }
poly-commit = { path = "../poly", default-features = false }
sp-std = { version = '3.0.0', default-features = false }

frame-system = { branch = 'v3.0.0', default-features = false, git = "https://github.com/KogarashiNetwork/zksubstrate" }
frame-support = { branch = 'v3.0.0', default-features = false, git = "https://github.com/KogarashiNetwork/zksubstrate" }

[dev-dependencies]
rand = "0.8.5"