[package]
name = "pallet-zk-rollup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
zkstd = { path = "../zkstd", default-features = false }
jub-jub = { path = "../jubjub", default-features = false }
ark-std = "0.4.0"
zero-plonk = { path = "../plonk", default-features = false }
ec-pairing = { path = "../pairing", default-features = false }
red-jubjub = { path = "../redjubjub", default-features = false}

[dev-dependencies]
rand = "0.8.5"
rand_core = { version="0.6.4", features = ["getrandom"] }
poly-commit = { path = "../poly", default-features = false }