[package]
authors = ['NoCtrlZ<shinsaku.ashizawa@artree.co.jp>']
description = 'twisted edwards curve implementation'
name = "eddy"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
