[package]
authors = [
    'ashWhiteHat<phantomofrotten@gmail.com>',
    'KiriosK<KiriosK@yandex.ru>'
]
name = "red-jubjub"
description = 'reddsa signature implementation on jubjub'
version = "0.0.13"
edition = "2021"
license = "Apache-2.0"
homepage = 'https://github.com/KogarashiNetwork/Kogarashi/'
repository = 'https://github.com/KogarashiNetwork/Kogarashi/'
readme = 'README.md'

[dependencies]
zkstd = { path = "../zkstd", default-features = false }
jub-jub = { path = "../jubjub", default-features = false }
bls-12-381 = { path = "../bls12_381", default-features = false }
blake2b_simd = { version = "1", default-features = false }
rand_core = { version="0.6.4", default-features = false }
zero-plonk = { path = "../plonk", default-features = false }
ec-pairing = { path = "../pairing", default-features = false }
poly-commit = {path = "../poly", default-features = false}

[dev-dependencies]
hex-literal = { version = "0.3.1", default-features = false }
rand = "0.8"

[features]
default = ["std"]
std = [
    "rand_core/getrandom"
]
