[package]
authors = [
    'ashWhiteHat<phantomofrotten@gmail.com>',
    'KiriosK<KiriosK@yandex.ru>'
]
name = "red-jubjub"
description = 'reddsa signature implementation on jubjub'
version = "0.0.15"
edition = "2021"
license = "Apache-2.0"
homepage = 'https://github.com/KogarashiNetwork/Kogarashi/'
repository = 'https://github.com/KogarashiNetwork/Kogarashi/'
readme = 'README.md'
categories = ["cryptography"]
keywords = ["zkp", "blockchain", "elliptic-curve"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs", "--html-in-header", "katex-header.html"]

[dependencies]
zkstd = { path = "../zkstd", default-features = false }
jub-jub = { path = "../jubjub", default-features = false }
bls-12-381 = { path = "../bls12_381", default-features = false }
blake2b_simd = { version = "1", default-features = false }
rand_core = { version="0.6.4", default-features = false }
serde = { version = "1.0.102", default-features = false, features = ["derive"] }
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }

[dev-dependencies]
hex-literal = { version = "0.3.1", default-features = false }
rand = "0.8"

[features]
default = ["std"]
std = [
    "rand_core/getrandom"
]
