[package]
name = "redjubjub"
version = "0.1.0"
edition = "2021"

[dependencies]
blake2b_simd = { version = "1", default-features = false }
rand_core = { version="0.6.4", default-features = false }

zkstd = { path = "../zkstd" }
jub-jub = { path = "../jubjub" }
bls-12-381 = { path = "../bls12_381" }

[dev-dependencies]
serde_json = { version = "1.0" }
hex-literal = { version = "0.3.1" }
