[package]
name = "ink_primitives"
version = "3.0.0"
authors = ["Parity Technologies <admin@parity.io>", "Robin Freyler <robin@parity.io>"]
edition = "2021"

license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/paritytech/ink"
documentation = "https://docs.rs/ink_primitives/"
homepage = "https://www.parity.io/"
description = "[ink!] Fundamental primitive types for ink! smart contracts."
keywords = ["wasm", "parity", "webassembly", "blockchain", "edsl"]
categories = ["no-std", "embedded"]
include = ["/Cargo.toml", "src/**/*.rs", "/README.md", "/LICENSE"]

[dependencies]
ink_prelude = { version = "3.0.0", path = "../prelude/", default-features = false }
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive", "full"] }
scale-info = { version = "2", default-features = false, features = ["derive"], optional = true }
cfg-if = "1"

[dev-dependencies]
criterion = "0.3.1"

[features]
default = ["std"]
std = [
    "ink_prelude/std",
    "scale/std",
    "scale-info/std",
]

[[bench]]
name = "bench"
path = "benches/bench.rs"
harness = false
