[package]
name = "zero-poly"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zero-jubjub = { default-features = false, path = "../jubjub" }

[dev-dependencies]
rand = "0.8"
