[package]
authors = ['NoCtrlZ<shinsaku.ashizawa@artree.co.jp>']
description = 'zkSNARK plonk pallet'
name = "zero-crypto"
version = "0.1.0"
edition = "2021"
homepage = 'https://github.com/zero-network/zero/'
readme = 'README.md'
repository = 'https://github.com/zero-network/zero/'
license = "Apache-2.0"

[dependencies]
parity-scale-codec = { version = "2", default-features = false, features = ["derive"] }
rand_core = { version="0.6", default-features = false }
sp-std = { version = '3.0.0', default-features = false }

[features]
default = ["std"]
std = []
