use crate::{Public, Seed, Signature, SIGNING_CTX};

use codec::Encode;
use sp_core::crypto::CryptoType;

#[cfg(feature = "std")]
use bip39::{Language, Mnemonic, MnemonicType};
#[cfg(feature = "std")]
use substrate_bip39::mini_secret_from_entropy;

#[cfg(feature = "full_crypto")]
use rand_core::SeedableRng;
#[cfg(feature = "full_crypto")]
use rand_xorshift::XorShiftRng;
#[cfg(feature = "full_crypto")]
use red_jubjub::{kogarashi_hash, Keypair, PublicKey, SecretKey};
#[cfg(feature = "full_crypto")]
use schnorrkel::SignatureResult;
#[cfg(feature = "full_crypto")]
use sp_core::crypto::{DeriveJunction, Pair as TraitPair, SecretStringError};
#[cfg(feature = "full_crypto")]
use zkstd::behave::SigUtils;

/// A key pair.
#[cfg(feature = "full_crypto")]
pub struct Pair(Keypair);

#[cfg(feature = "full_crypto")]
impl Pair {
    /// Get the seed for this key.
    pub fn seed(&self) -> Seed {
        self.0.secret.to_bytes()
    }

    /// Exactly as `from_string` except that if no matches are found then, the the first 32
    /// characters are taken (padded with spaces as necessary) and used as the MiniSecretKey.
    #[cfg(feature = "std")]
    pub fn from_legacy_string(s: &str, password_override: Option<&str>) -> Pair {
        Self::from_string(s, password_override).unwrap_or_else(|_| {
            let mut padded_seed: Seed = [' ' as u8; 32];
            let len = s.len().min(32);
            padded_seed[..len].copy_from_slice(&s.as_bytes()[..len]);
            Self::from_seed(&padded_seed)
        })
    }
    /// Make a new key pair from binary data derived from a valid seed phrase.
    ///
    /// This uses a key derivation function to convert the entropy into a seed, then returns
    /// the pair generated from it.
    pub fn from_entropy(entropy: &[u8], password: Option<&str>) -> (Pair, Seed) {
        let seed = mini_secret_from_entropy(entropy, password.unwrap_or(""))
            .expect("32 bytes can always build a key; qed")
            .to_bytes();

        let secret = SecretKey::new(kogarashi_hash(&seed));
        (Self(Keypair::new(secret)), secret.to_bytes())
    }

    /// Verify a signature on a message. Returns `true` if the signature is good.
    /// Supports old 0.1.1 deprecated signatures and should be used only for backward
    /// compatibility.
    pub fn verify_deprecated<M: AsRef<[u8]>>(sig: &Signature, message: M, pubkey: &Public) -> bool {
        // Match both schnorrkel 0.1.1 and 0.8.0+ signatures, supporting both wallets
        // that have not been upgraded and those that have.
        match PublicKey::from_bytes(*pubkey.as_ref()) {
            Some(pk) => pk
                .verify_simple_preaudit_deprecated::<SignatureResult<()>>(
                    SIGNING_CTX,
                    message.as_ref(),
                    &sig.0[..],
                )
                .is_ok(),
            None => false,
        }
    }
}

#[cfg(feature = "full_crypto")]
impl TraitPair for Pair {
    type Public = Public;
    type Seed = Seed;
    type Signature = Signature;
    type DeriveError = DeriveError;

    /// Generate new secure (random) key pair and provide the recovery phrase.
    ///
    /// You can recover the same key later with `from_phrase`.
    fn generate_with_phrase(password: Option<&str>) -> (Pair, String, Seed) {
        let mnemonic = Mnemonic::new(MnemonicType::Words12, Language::English);
        let phrase = mnemonic.phrase();
        let (pair, seed) = Self::from_phrase(phrase, password)
            .expect("All phrases generated by Mnemonic are valid; qed");
        (pair, phrase.to_owned(), seed)
    }

    /// Generate key pair from given recovery phrase and password.
    fn from_phrase(
        phrase: &str,
        password: Option<&str>,
    ) -> Result<(Pair, Seed), SecretStringError> {
        Mnemonic::from_phrase(phrase, Language::English)
            .map_err(|_| SecretStringError::InvalidPhrase)
            .map(|m| Self::from_entropy(m.entropy(), password))
    }

    /// Make a new key pair from secret seed material.
    ///
    /// You should never need to use this; generate(), generate_with_phrase
    fn from_seed(seed: &Seed) -> Pair {
        Self::from_seed_slice(&seed[..]).expect("seed has valid length; qed")
    }

    /// Make a new key pair from secret seed material. The slice must be 32 bytes long or it
    /// will return `None`.
    ///
    /// You should never need to use this; generate(), generate_with_phrase
    fn from_seed_slice(seed_slice: &[u8]) -> Result<Pair, SecretStringError> {
        let secret = SecretKey::new(kogarashi_hash(seed_slice));
        Ok(Self(Keypair::new(secret)))
    }

    /// Derive a child key from a series of given junctions.
    fn derive<Iter: Iterator<Item = DeriveJunction>>(
        &self,
        path: Iter,
        _seed: Option<Seed>,
    ) -> Result<(Pair, Option<Seed>), DeriveError> {
        let mut acc = self.0.secret.to_bytes();
        for j in path {
            match j {
                DeriveJunction::Soft(_cc) => return Err(DeriveError::SoftKeyInPath),
                DeriveJunction::Hard(cc) => acc = derive_hard_junction(&acc, &cc),
            }
        }
        Ok((Self::from_seed(&acc), Some(acc)))
    }

    /// Get the public key.
    fn public(&self) -> Public {
        Public(self.0.public.to_bytes())
    }

    /// Sign a message.
    fn sign(&self, message: &[u8]) -> Signature {
        let mut rng = XorShiftRng::from_seed([
            0xbc, 0x4f, 0x6d, 0x44, 0xd6, 0x2f, 0x27, 0x6c, 0xb9, 0x63, 0xaf, 0xd0, 0x54, 0x55,
            0x86, 0x3d,
        ]);
        let r = self.0.secret.sign(message, &mut rng);
        Signature(r.to_bytes())
    }

    /// Verify a signature on a message. Returns true if the signature is good.
    fn verify<M: AsRef<[u8]>>(sig: &Self::Signature, message: M, pubkey: &Self::Public) -> bool {
        Self::verify_weak(&sig.0[..], message.as_ref(), pubkey)
    }

    /// Verify a signature on a message. Returns true if the signature is good.
    ///
    /// This doesn't use the type system to ensure that `sig` and `pubkey` are the correct
    /// size. Use it only if you're coming from byte buffers and need the speed.
    fn verify_weak<P: AsRef<[u8]>, M: AsRef<[u8]>>(sig: &[u8], message: M, pubkey: P) -> bool {
        let public_key = match PublicKey::from_raw_bytes(pubkey.as_ref()) {
            Some(pk) => pk,
            None => return false,
        };

        let sig = match red_jubjub::Signature::from_raw_bytes(sig) {
            Some(s) => s,
            None => return false,
        };

        public_key.validate(message.as_ref(), sig)
    }

    /// Return a vec filled with raw data.
    fn to_raw_vec(&self) -> Vec<u8> {
        self.0.secret.to_bytes().to_vec()
    }
}

#[cfg(feature = "full_crypto")]
impl Clone for Pair {
    fn clone(&self) -> Self {
        Pair(Keypair {
            public: self.0.public.clone(),
            secret: SecretKey::from_bytes(self.0.secret.to_bytes())
                .expect("key is always the correct size; qed"),
        })
    }
}

/// Derive a single hard junction.
#[cfg(feature = "full_crypto")]
fn derive_hard_junction(secret_seed: &Seed, cc: &[u8; 32]) -> Seed {
    ("RedjubjubHDKD", secret_seed, cc).using_encoded(|data| {
        let mut res = [0u8; 32];
        res.copy_from_slice(blake2_rfc::blake2b::blake2b(32, &[], data).as_bytes());
        res
    })
}

/// An error when deriving a key.
#[cfg(feature = "full_crypto")]
#[derive(Debug)]
pub enum DeriveError {
    /// A soft key was found in the path (and is unsupported).
    SoftKeyInPath,
}

#[cfg(feature = "full_crypto")]
impl CryptoType for Pair {
    type Pair = Pair;
}
