[package]
authors = ['NoCtrlZ<phantomofrotten@gmail.com>']
name = "zero-bls12-381"
description = 'lifted elgamal encryption implementation'
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
