[package]
name = "dsa"
version = "0.1.0"
edition = "2021"

[dependencies]
zero-jubjub = { path = "../jubjub" }
zero-crypto = { path = "../crypto" }

[dev-dependencies]
secp256k1 = { version = "0.26.0" }
bitcoin_hashes = { version = "0.11" }
