[package]
name = "dsa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
secp256k1 = { version = "0.26.0" }
bitcoin_hashes = { version = "0.11" }