[package]
authors = [
    'ashWhiteHat<phantomofrotten@gmail.com>',
    'KiriosK<KiriosK@yandex.ru>'
]
name = "zero-r1cs"
description = 'r1cs implementation'
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
homepage = 'https://github.com/zero-network/zero/'
repository = 'https://github.com/zero-network/zero/'
readme = 'README.md'

[dependencies]
hashbrown = {version = "0.13.2", default-features=false, features = ["ahash"]}
merlin = {version = "3.0", default-features = false}
rand_core = { version="0.6", default-features = false }

zero-crypto = { path = "../crypto", default-features = false }
zero-bls12-381 = { path = "../bls12_381", default-features = false }
zero-kzg = { path = "../kzg", default-features = false }
zero-pairing = {path = "../pairing", default-features = false}

[dev-dependencies]
rand = "0.8"

[features]
default = ["std"]
std = []
