[package]
name = "pallet-confidential-transfer"
description = 'confidential transfer pallet'
edition = '2018'
homepage = 'https://github.com/zero-network/zero'
license = "Apache-2.0"
version = "0.1.0"
readme = 'README.md'
repository = 'https://github.com/zero-network/zero'


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
