[package]
name = "redjubjub"
version = "0.1.0"
edition = "2021"

[dependencies]
codec = { default-features = false, features = ['derive'], package = 'parity-scale-codec', version = '2.0.0' }
sp-runtime = { tag = "v3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
sp-runtime-interface = { tag = "v3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
sp-std = { tag = "v3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
sp-core = { tag = "v3.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }

strum = { version = "0.20.0", features = ["derive"] }
blake2b_simd = { version = "1", default-features = false }
rand_xorshift = { version = "0.3", default-features = false }
rand_core = { version="0.6.4", default-features = false }

hex = { version = "0.4", default-features = false, optional = true }
tiny-bip39 = { version = "0.8", optional = true }
thiserror = { version = "1.0.21", optional = true }
blake2-rfc = { version = "0.2.18", default-features = false, optional = true }
lazy_static = { version = "1.4.0",  default-features = false, optional = true }
substrate-bip39 = { version = "0.4.2", optional = true }
serde = { version = "1.0.102", features = ["derive"], optional = true }
schnorrkel = { version = "0.9.1", features = ["preaudit_deprecated", "u64_backend"], default-features = false, optional = true }

zkstd = { default-features = false, path = "../../primitive/zkstd" }
bls-12-381 = { default-features = false, path = "../../primitive/bls12_381" }
red-jubjub = { default-features = false, path = '../../primitive/redjubjub' }

[dev-dependencies]
jub-jub = { default-features = false, path = '../../primitive/jubjub' }
serde_json = { version = "1.0" }
hex-literal = { version = "0.3.1" }

[features]
default = ['std']
full_crypto = [
	"hex",
	"blake2-rfc",
	"schnorrkel",
    "sp-core/full_crypto",
    "sp-runtime-interface/disable_target_static_assertions",
]
runtime-benchmarks = [
    'sp-runtime/runtime-benchmarks',
]
std = [
    'full_crypto',
	"serde",
    'codec/std',
    'sp-std/std',
    'sp-core/std',
    'sp-runtime/std',
	"substrate-bip39",
	"tiny-bip39",
	"lazy_static",
	"schnorrkel/std",
	"schnorrkel/serde",
	"sp-runtime-interface/std",
]
