[package]
name = "redjubjub"
version = "0.1.0"
edition = "2021"

[dependencies]
sp-std = { version = '3.0.0', default-features = false }
sp-core = { version = "3.0.0", default-features = false }
codec = { default-features = false, features = ['derive'], package = 'parity-scale-codec', version = '2.0.0' }
sp-runtime = { version = "3.0.0", default-features = false }
sp-runtime-interface = { version = "3.0.0", default-features = false }
substrate-bip39 = { version = "0.4.2", default-features = false }

tiny-bip39 = { version = "0.8", default-features = false }
strum = { version = "0.20.0", features = ["derive"] }
lazy_static = { version = "1.4.0", default-features = false }
blake2b_simd = { version = "1", default-features = false }
blake2-rfc = { version = "0.2.18", default-features = false }
serde = { version = "1.0.102", default-features = false, features = ["derive"] }
hex = { version = "0.4", default-features = false }
schnorrkel = { version = "0.9.1", features = ["preaudit_deprecated", "u64_backend"], default-features = false }
thiserror = { version = "1.0.21", default-features = false }
rand_xorshift = { version = "0.3", default-features = false }
rand_core = { version="0.6.4", default-features = false }

zkstd = { default-features = false, path = "../../primitive/zkstd" }
bls-12-381 = { default-features = false, path = "../../primitive/bls12_381" }
red-jubjub = { default-features = false, path = '../../primitive/redjubjub' }

[features]
default = ['std']
full_crypto = [
    "sp-runtime-interface/disable_target_static_assertions",
]
runtime-benchmarks = [
    'sp-runtime/runtime-benchmarks',
]
std = [
    'full_crypto',
    'codec/std',
    'sp-std/std',
    'sp-core/std',
    'sp-runtime/std',
]
