[package]
name = "zero-circuits"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zero-plonk = { path = "../plonk" }
zero-jubjub = { path = "../jubjub" }
zero-crypto = { path = "../crypto" }

[dev-dependencies]
rand = "0.8"
ark-std = { version = "0.3", features = ["print-trace"] }
