[package]
name = "zero-pairing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zero-crypto = { path = '../crypto' }
zero-bls12-381 = { version = '0.1.0', path = '../bls12_381' }

[dev-dependencies]
rand_xorshift = { version = "0.3", default-features = false }
rand = { version = "0.8", default-features = false }
