[package]
name = "zero-pairing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zero-crypto = { path = '../crypto' }
zero-bls12-381 = { version = '0.1.0', path = '../bls12_381' }

[dev-dependencies]
rand_core = { version="0.6", default-features = false }
