[package]
name = "zero-pairing"
version = "0.2.0"
edition = "2021"
description = 'lifted elgamal encryption implementation'
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zero-crypto = { version = '0.2.1', default-features = false }
zero-bls12-381 = { version = '0.2.0', default-features = false }

[dev-dependencies]
rand_xorshift = { version = "0.3", default-features = false }
rand = { version = "0.8", default-features = false }
