[package]
name = "zksnarks"
version = "0.1.0"
edition = "2021"

[dependencies]
zkstd = { path = "../zkstd", default-features = false }
poly-commit = { path = "../poly", default-features = false }
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }
