[package]
name = "zksnarks"
version = "0.1.0"
edition = "2021"
categories = ["cryptography"]
keywords = ["zkp", "blockchain", "elliptic-curve"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs", "--html-in-header", "katex-header.html"]

[dependencies]
zkstd = { path = "../zkstd", default-features = false }
jub-jub = { path = "../jubjub", default-features = false }
poly-commit = { path = "../poly", default-features = false }
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }
merlin = { version = "3.0", default-features = false }
