[package]
authors = [
    'ashWhiteHat<phantomofrotten@gmail.com>',
    'KiriosK<KiriosK@yandex.ru>'
]
name = "pallet-encrypted-balance"
version = "0.2.3"
edition = "2021"
license = "Apache-2.0"
homepage = 'https://github.com/zero-network/zero/'
repository = 'https://github.com/zero-network/zero/'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.102", default-features = false, features = ["derive"] }
codec = { version = "2.1.0", default-features = false, package = "parity-scale-codec", features = ["derive"] }
sp-std = { version = "3.0.0", default-features = false }
sp-runtime = { version = "3.0.0", default-features = false }
sp-arithmetic = { version = "3.0.0", default-features = false }
frame-support = { version = "3.0.0", default-features = false }
frame-system = { version = "3.0.0", default-features = false }
zero-elgamal = { path = '../../primitive/elgamal', default-features = false }
zero-jubjub = { path = '../../primitive/jubjub', default-features = false }
zero-pairing = { path = '../../primitive/pairing', default-features = false }
zero-crypto = { path = "../../primitive/crypto", default-features = false }

[dev-dependencies]
sp-io = { version = "3.0.0", default-features = false }
sp-core = { version = "3.0.0", default-features = false }
pallet-transaction-payment = { version = "3.0.0", default-features = false }
proptest = "1"

[features]
default = ["std"]
std = [
    'codec/std',
    "frame-support/std",
	'frame-system/std',
]
