[package]
name = "zknova"
description = 'nova implementation'
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"
homepage = 'https://github.com/KogarashiNetwork/Kogarashi/'
repository = 'https://github.com/KogarashiNetwork/Kogarashi/'
readme = 'README.md'
categories = ["cryptography"]
keywords = ["zkp", "blockchain", "elliptic-curve"]

[dependencies]
r1cs = { path = "../r1cs", default-features = false }
zkstd = { path = "../zkstd", default-features = false }

[features]
default = ["std"]
std = [
    "zkstd/std"
]
