[package]
name = "ink_lang_macro"
version = "3.0.0"
authors = ["Parity Technologies <admin@parity.io>", "Robin Freyler <robin@parity.io>"]
edition = "2021"

license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/paritytech/ink"
documentation = "https://docs.rs/ink_lang_macro/"
homepage = "https://www.parity.io/"
description = "[ink!] Rust based eDSL for writing smart contracts for Substrate"
keywords = ["wasm", "parity", "webassembly", "blockchain", "edsl"]
categories = ["no-std", "embedded"]
include = ["Cargo.toml", "src/**/*.rs", "README.md", "LICENSE"]

[dependencies]
ink_lang_ir = { version = "3.0.0", path = "../ir", default-features = false }
ink_lang_codegen = { version = "3.0.0", path = "../codegen", default-features = false }
ink_primitives = { version = "3.0.0", path = "../../primitives/", default-features = false }

scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
syn = "1"
proc-macro2 = "1"

[dev-dependencies]
ink_metadata = { version = "3.0.0", path = "../../metadata/" }
ink_env = { version = "3.0.0", path = "../../env/" }
ink_storage = { version = "3.0.0", path = "../../storage/" }
ink_lang = { version = "3.0.0", path = ".." }
scale-info = { version = "2", default-features = false, features = ["derive"] }

[lib]
name = "ink_lang_macro"
proc-macro = true

[features]
default = ["std"]
std = [
    "scale/std",
    "ink_lang_ir/std",
    "ink_primitives/std",
]
