[package]
authors = [
    'ashWhiteHat<phantomofrotten@gmail.com>',
    'KiriosK<KiriosK@yandex.ru>'
]
name = 'pallet-plonk'
description = 'zkSNARK plonk pallet'
version = '0.2.2'
edition = '2021'
license = "Apache-2.0"
homepage = 'https://github.com/zero-network/zero/'
repository = 'https://github.com/zero-network/zero/'
readme = 'README.md'

[dependencies]
codec = { default-features = false, features = ['derive'], package = 'parity-scale-codec', version = '2.0.0' }
frame-system = { default-features = false, version = '3.0.0' }
frame-support = { default-features = false, version = '3.0.0' }
frame-benchmarking = { default-features = false, optional = true, version = '3.1.0' }
zero-plonk = { path = "../../primitive/plonk", default-features = false }
zero-jubjub = { path = "../../primitive/jubjub", default-features = false }
zero-crypto = { path = "../../primitive/crypto", default-features = false }
zero-bls12-381 = { path = "../../primitive/bls12_381", default-features = false }
rand_xorshift = { git = "https://github.com/zero-network/rngs", branch = "master", default-features = false }

[dev-dependencies]
serde = { version = "1.0.125", default-features = false, features = ["derive"] }
rand = { version = "0.8", default-features = false }
sp-core = { version = '3.0.0', default-features = false }
sp-io = { version = '3.0.0', default-features = false }
sp-runtime = { version = '3.0.0', default-features = false }

[features]
default = ["std"]
std = [
    'codec/std',
    'frame-support/std',
	'frame-system/std',
    'frame-benchmarking/std',
    'zero-plonk/std',
    'sp-core/std',
    'sp-io/std',
    'sp-runtime/std',
]
