[package]
authors = ['NoCtrlZ<phantomofrotten@gmail.com>']
description = 'zkSNARK plonk pallet'
edition = '2018'
homepage = 'https://github.com/zero-network/zero'
license = "Apache-2.0"
name = 'pallet-plonk'
readme = 'README.md'
repository = 'https://github.com/zero-network/zero'
version = '0.2.2'

[dependencies]
codec = { default-features = false, features = ['derive'], package = 'parity-scale-codec', version = '2.0.0' }
frame-system = { default-features = false, version = '3.0.0' }
frame-support = { default-features = false, version = '3.0.0' }
frame-benchmarking = { default-features = false, optional = true, version = '3.1.0' }
zero-plonk = { path = "../../primitive/plonk", default-features = false }
zero-jubjub = { path = "../../primitive/jubjub", default-features = false }
zero-crypto = { path = "../../primitive/crypto", default-features = false }
zero-bls12-381 = { path = "../../primitive/bls12_381", default-features = false }
rand_xorshift = { git = "https://github.com/zero-network/rngs", branch = "master", default-features = false }

[dev-dependencies]
serde = { version = "1.0.125", default-features = false, features = ["derive"] }
rand = { version = "0.8", default-features = false }
sp-core = { default-features = false, version = '3.0.0' }
sp-io = { default-features = false, version = '3.0.0' }
sp-runtime = { default-features = false, version = '3.0.0' }

[features]
default = ["std"]
std = [
    "frame-support/std"
]
