name: Merged Check
on:
  push:
    branches: [ master ]

jobs:
  test:
    name: Production Environment Unit Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Update submodules
        id: update
        run: git submodule update --remote --recursive
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --all --all-features

  bench:
    name: Benchmark
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Update submodules
        id: update
        run: git submodule update --remote --recursive
      - uses: actions-rs/toolchain@v1
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: bench
