name: Integration Test
on:
  pull_request:
    branches: [ master, develop ]

jobs:
  node:
        if: contains(github.event.pull_request.labels.*.name, 'node')
        name: Node Test
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
          with:
            submodules: recursive
        - name: Update submodules
          id: update
          run: git submodule update -i
        - name: checkout pushed commit
          uses: actions/checkout@v2
          with:
            ref: ${{ github.event.pull_request.head.sha }}
        - name: Run docker compose
          run: docker-compose up
