name: Integration Test
on:
  pull_request:
    branches: [ master, develop ]

jobs:
  node:
        if: contains(github.event.pull_request.labels.*.name, 'node')
        name: Node Test
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
          with:
            submodules: recursive
        - uses: actions/checkout@v2
        - name: Generate SSH
          run: ssh-keygen -t rsa -b 4096 -C "sample" -f ~/.ssh/id_rsa -N ""
        - name: Registry Auth
          run: echo "${{ secrets.REGISTRY_ACCESS_TOKEN }}" | docker login docker.pkg.github.com -u '${{ secrets.ACCOUNT_NAME }}' --password-stdin
        - name: Update submodules
          id: update
          run: git submodule update -i
        - name: checkout pushed commit
          uses: actions/checkout@v2
          with:
            ref: ${{ github.event.pull_request.head.sha }}
        - name: Run docker compose
          run: docker-compose up
