name: Publish Package
on:
  pull_request:
    branches: [ master, develop ]

jobs:
  node:
        if: contains(github.event.pull_request.labels.*.name, 'package')
        name: Node RPC Test
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
          with:
            submodules: recursive
        - uses: actions/checkout@v2
        - name: Generate SSH
          run: ssh-keygen -t rsa -b 4096 -C "sample" -f ~/.ssh/id_rsa -N ""
        - name: Registry Auth
          run: echo "${{ secrets.REGISTRY_ACCESS_TOKEN }}" | docker login ghcr.io -u '${{ secrets.ACCOUNT_NAME }}' --password-stdin
        - name: Publish Package
          id: update
          run: git submodule update -i
        - uses: actions-rs/toolchain@v1
        - run: sh scripts/package.sh
