name: Pull Reqeust Check
on:
  pull_request:
    branches: [ master, develop ]

jobs:
  fmt:
    if: github.event.pull_request.draft == false
    name: Code Format Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
      if: github.event.pull_request.draft == false
      name: Clippy Check
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - uses: actions-rs/toolchain@v1
          with:
            components: clippy
        - uses: actions-rs/cargo@v1
          with:
            command: clippy
            args: --workspace --all-features

  test:
    if: github.event.pull_request.draft == false
    name: Calculate Code Coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.22.0'
          args: '--release --all-features --workspace --no-fail-fast --engine Llvm --out Lcov'
          out-type: 'Lcov'
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
