name: Code Climate Test Coverage

on:
  pull_request:
  push:
    branches:
      - main
      - test-coverage

jobs:
  codeclimate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Update submodules
        id: update
        run: git submodule update --remote --recursive
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-11-14

          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --workspace --no-fail-fast
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
          RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
      - uses: actions-rs/grcov@v0.1
        with:
          branch: true
          llvm: true
          ignore-not-existing: true
          output-type: lcov
          output-path: ./lcov.info
