[package]
name = "kzg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zero-crypto = { version = '0.1.0', path = '../crypto' }
parity-scale-codec = { version = "2", default-features = false, features = ["derive"] }
rand = { version = "0.8", default-features = false }
rand_xorshift = { version = "0.3", default-features = false }
